---
title: "Parsing Canadian Paliament List"
author: "Akitaka Matsuo"
date: "10/30/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


In this file, we will download an XML file of the list of canadian parliament members. The url is
https://www.ourcommons.ca/Parliamentarians/en/members/export?output=XML.

## Load libraries
```{r}
library(xml2)
library(rvest)
library(dplyr)
```

## Get the file

```{r}
url <- "https://www.ourcommons.ca/Parliamentarians/en/members/export?output=XML"
xml_mps_can <- read_xml(url)
str(xml_mps_can)

```



```{r}
mps_nodes<- xml_nodes(xml_mps_can, xpath = "//MemberOfParliament")
length(mps_nodes)
```

Using the first element of the list of nodes, let's try to make a list of members.

```{r}
as_list(mps_nodes[[1]])
```

```{r}
unlist(as_list(mps_nodes[[1]]))
```

```{r}
as.list(unlist(as_list(mps_nodes[[1]])))
```

```{r}
tmp <- data.frame(as.list(unlist(as_list(mps_nodes[[1]]))), stringsAsFactors = FALSE)
View(tmp)
```

In the code chunk above, we are finally able to make a list of mps
```{r}
## first define a function to process each member
node_processing <- function(x) {
  data.frame(as.list(unlist(as_list(x))), stringsAsFactors = FALSE)
}

data_list <- list()
for(i in 1:length(mps_nodes)){
  nod <- mps_nodes[[i]]
  data_list[[i]] <- node_processing(nod)
}

## easier
data_list <- lapply(mps_nodes, node_processing)

data_all <- bind_rows(data_list) # rbind() does not work because some elements are missing for some members. 
head(data_all)
```

We could do this with `dplyr` based method. That would be much more intuitive.
```{r}

node_processing_2 <- function(x) {
  # the following is exactly the same as 
  # data.frame(as.list(unlist(as_list(x))), stringsAsFactors = FALSE)
  # but this is probably easier to read
  as_list(x) %>% 
    unlist %>% 
    as.list %>% 
    data.frame(stringsAsFactors = FALSE)
}

## use lapply() instead of for loop
data_all_2 <- lapply(mps_nodes, node_processing_2) %>% # first run lapply to the list of nodes
  bind_rows() # then use bind_rows() 
head(data_all_2)
```

